from __future__ import annotations

from rest_framework import serializers


class GeneratedTaskSerializer(serializers.Serializer):
    """A single actionable task generated by the LLM."""

    title = serializers.CharField(max_length=200)
    description = serializers.CharField()
    estimated_days = serializers.IntegerField(min_value=1)


class GeneratedPhaseSerializer(serializers.Serializer):
    """A roadmap phase grouping related tasks."""

    title = serializers.CharField(max_length=200)
    objective = serializers.CharField()
    duration_weeks = serializers.IntegerField(min_value=1)
    tasks = GeneratedTaskSerializer(many=True)


class GeneratedRoadmapSerializer(serializers.Serializer):
    """Validated roadmap shape returned to API consumers."""

    roadmap_title = serializers.CharField(max_length=255)
    summary = serializers.CharField()
    phases = GeneratedPhaseSerializer(many=True)


class RoadmapTaskResponseSerializer(serializers.Serializer):
    """Async task response returned when roadmap generation is queued."""

    task_id = serializers.CharField(label="Task ID", help_text="Celery task identifier for polling.")
    status = serializers.CharField(label="Status", help_text="Current queue status, usually queued.")


class RoadmapTaskStatusSerializer(serializers.Serializer):
    """Serialized Celery task state for frontend polling."""

    task_id = serializers.CharField(label="Task ID", help_text="Celery task identifier.")
    state = serializers.CharField(label="State", help_text="Celery task state such as PENDING, STARTED, SUCCESS, or FAILURE.")
    status = serializers.CharField(label="Status", help_text="Human readable task status message.")
    result = serializers.JSONField(required=False, allow_null=True, label="Result", help_text="Task result payload when available.")
    error = serializers.CharField(required=False, allow_blank=True, allow_null=True, label="Error", help_text="Error message when the task fails.")


