# Generated by Django 6.0.3 on 2026-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendationResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        db_index=True,
                        help_text="Career direction (e.g., backend, frontend, data science)",
                        max_length=120,
                    ),
                ),
                (
                    "min_english_level",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        default="A1",
                        help_text="Minimum required English level",
                        max_length=2,
                    ),
                ),
                (
                    "max_english_level",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        default="C2",
                        help_text="Maximum English level for which this resource is suitable",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("video", "Video"),
                            ("article", "Article"),
                            ("practice", "Practice"),
                            ("book", "Book"),
                        ],
                        default="course",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Lower value = higher priority in recommendations",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "recommendation resource",
                "verbose_name_plural": "recommendation resources",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="recommendationresource",
            index=models.Index(
                fields=["direction", "is_active"],
                name="recommendat_directi_4f2c1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationresource",
            index=models.Index(
                fields=["min_english_level", "max_english_level"],
                name="recommendat_min_eng_8c9d3b_idx",
            ),
        ),
    ]

