# Generated by Django 6.0.3 on 2026-04-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recommendationresource',
            new_name='recommendat_directi_7a4df6_idx',
            old_name='recommendat_directi_4f2c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationresource',
            new_name='recommendat_min_eng_710c3a_idx',
            old_name='recommendat_min_eng_8c9d3b_idx',
        ),
    ]
